### ISSUE TITLE
Can't pass `mainTarget` to `PreviewModels.stencil`

### ISSUE THREAD

**Issue by markst** [BarredEwe/Prefire#20]
## Context 🕵️‍♀️

Inside `PreviewModels.stencil` we have a conditional import statement:
```
{% if argument.mainTarget %}
@testable import {{ argument.mainTarget }}
{% endif %}
```

## What 🌱
Where as the `PrefireTestsPlugin` can be provided with a `mainTarget` argument. 
It seems the `PrefirePlaybookPlugin` has no support for passing the `mainTarget`?

## Proposal 🎉
Think this might be as simple as passing:
```swift
"--args",
"mainTarget=\(targetName)",
```
to the `PrefireTestsPlugin.Command`

**Comment by Foixa** [comment]
When using XCodegen, it lists the targets alphabetically. Stencil uses the first target as mainTarget. I have now fixed this manually. Is there a better solution?

**Comment by BarredEwe** [comment]
@Foixa I think you can create a **.prefire.yml** configuration file in the root of the project. Then add the necessary `Target` to this file.

```yaml
test_configuration:
  - target: YourTarget 
```

**Comment by BarredEwe** [comment]
I added parameter forwarding in the latest release. 
```yml
test_configuration:
  - imports:
    - UIKit
    - SwiftUI
  - testable_imports:
    - Prefire

prefire_configuration:
  - imports:
    - UIKit
    - Foundation
  - testable_imports:
    - SwiftUI
```
You can try it 🚀
