### ISSUE TITLE
No such module Prefire

### ISSUE THREAD

**Issue by thannn** [BarredEwe/Prefire#44]
## Context 🕵️‍♀️
Attempting to generate snapshot tests.

1. Installed Prefire according to the readme:

- added it as dependency to my package
- added it as plugin to my test target

2. Using #Preview for SwiftUI previews.

3. .prefire.yml:
```
test_configuration:
  - target: RedactedTests
  - simulator_device: "iPhone15,4"
  - required_os: 16
  - preview_default_enabled: true
  - imports:
    - Foundation
    - UIKit
  - testable_imports:
    - Prefire
```

## What 🌱
The generated code (PreviewTests.generated.swift) throws error `No such module Prefire` upon line `import Prefire`.
