### ISSUE TITLE
.prefire.yml ignored by PrefirePlaybook plugin 

### ISSUE THREAD

**Issue by szymon-heetch** [BarredEwe/Prefire#52]
## Context 🕵️‍♀️
Just updated from 1.5.0 to 2.3.0. I use playbook and tests plugins for my target. 
Configuration file uses `- preview_default_enabled: false` to manually choose previews for snapshots and playbook view.

`.prefire.yml` content:
```yaml
test_configuration:
  - preview_default_enabled: false
  - target: [Redacted]
  - simulator_device: "iPhone15,2"
  - required_os: 16
  - snapshot_devices:
    - iPhone 14 Pro

prefire_configuration:
  - preview_default_enabled: false

```

## What 🌱
Running Prefire Tests plugin:
![PrefireTests](https://github.com/BarredEwe/Prefire/assets/78354061/8ebc7265-cd3c-47e1-9264-f9d9c083f17c)

Running Prefire Playbook plugin:
![PrefirePlaybook](https://github.com/BarredEwe/Prefire/assets/78354061/e35c33d9-2a36-4cc3-9e2b-52fe83a85efc)

**Comment by BarredEwe** [comment]
@szymon-heetch Thanks for starting the issue!
I posted a new version with a fix for this: https://github.com/BarredEwe/Prefire/releases/tag/2.3.1

**Comment by szymon-heetch** [comment]
Thanks for fast reply @BarredEwe! 
I see some inconsistencies tho.
I still use config above. Here what I observed:

### PrefirePlaybookPlugin
#### `#Preview` macro
- `preview_default_enabled: false` setting is still ignored - all my previews are automatically generated. When I add `.prefireIgnored()` explicitly, then it's skipped from generation (correct behavior), but I think it should be skipped automatically and `.prefireEnabled()` should mark previews for generation only. 
#### `PrefireProvider` protocol conformance
-  all previews marked with above protocol are correctly generated. I believe setting `preview_default_enabled: false` only applies to macros (correct me if I'm wrong).

### PrefireTestPlugin
Nothing is generated in both cases (`#Preview` and `PrefireProvider`)

Running Test plugin with config:
```
test_configuration:
  ....
  - preview_default_enabled: true

prefire_configuration:
  - preview_default_enabled: false
```
gets last `preview_default_enabled: false` settings (`test_configuration` and `prefire_configuration` sections are ignored).

### My test scenario
- Single framework
- Use configuration `.yml` above
- **Exclusively** use `PrefirePlaybookPlugin` or `PrefireTestPlugin` (never both at the same time)

**Comment by BarredEwe** [comment]
There is a problem in the documentation Readme.md . That's not what the playbook configuration is called right now.

```yaml
test_configuration:
  - preview_default_enabled: true

playbook_configuration:
  - preview_default_enabled: false
```
